name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install required linux packages for gio
      run: sudo apt update && sudo apt install -y --no-install-recommends libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Tests
      run: go test ./...
